name: Test, build and publish adapters

on:
  push:
    branches:
      - 'master'
    paths:
      - 'react-17-adapter/**'
      - '.github/workflows/adapter-release.yaml'

env:
  CI: true
jobs:
  test-build-publish:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Build core
        run: |
          npm ci
          npm test
          npm run build
      - name: Install dependencies
        working-directory: ./react-17-adapter
        run: npm ci
      - name: Build
        working-directory: ./react-17-adapter
        run: npm run build
      - name: Publish
        working-directory: ./react-17-adapter
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
